version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - yolo-network

  backend:
    image: alvinrombora/yolo-backend:v1.0.0
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo/yolomy
    networks:
      - yolo-network

  client:
    image: alvinrombora/yolo-client:v1.0.0
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

volumes:
  mongo-volume:
    driver: local
