version: '3'

services:
  backend:
    image: alvinrombora/yolo-backend:v1.0.0
    ports:
      - 5000:5000
    networks:
      - yolo-network

  client:
    image: alvinrombora/yolo-client:v1.0.0
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge
